### ISSUE TITLE
redigera/radera problem som jag själv lagt till

### ISSUE THREAD

**Issue by jonaswahlgren** [FelixAbrahamsson/boardclimbs-feedback#1]
Det kanske är planen att implementera men det hade varit schysst att kunna redigera/ta bort problem som jag har lagt till. Jag la nämligen in fel grepp och nu går det inte att göra något åt det vad jag förstår

**Comment by jonaswahlgren** [comment]
nvm såg nu att man gör det under "tick"

**Comment by FelixAbrahamsson** [comment]
<3 tack för feedback! Det är ju en jäkligt dåld feature atm, ska se till att göra den tydligare :)
