### ISSUE TITLE
Wall photo orientation

### ISSUE THREAD

**Issue by Mul4n** [FelixAbrahamsson/boardclimbs-feedback#2]
Hi,
First of all, thank you for this project, it looks awesome.

I tried to create a wall with a vertical photo, but on upload it seems to rotate it to landscape. This makes it quite hard to use.
Wall id : a2dc725b-22f6-44b6-b97b-c54d0f586f49 for you to see.

Is it something that you would concider handling or should I take a landscape photo of my wall ?

Thank you !

**Comment by FelixAbrahamsson** [comment]
Thanks for the feedback! I've seen this happen for others and have personally experienced this as well, not sure why it happens. It's high on the priority list (probably the next thing I'll tackle) to solve this, I think I'll just add a minimal photo editor to the frontend where you can rotate + crop the image after you upload it.

**Comment by FelixAbrahamsson** [comment]
This has now been fixed and deployed :)
